config/routes.rb
Rails.application.routes.draw do
  get 'manager/index'
  devise_for :users
  resources :users
  resources :lines
  resources :orders do
    resources :payments, only: [:new] do
      collection do
        get 'success'
      end
    end

    member do
      post 'produce'
      post 'deliver'
    end
  end


  resources :tables do
    member do
      get 'qrcode'
    end
  end
  resources :roles
  resources :venues do
    member do
      get 'produce'
      get 'deliver'
    end
  end
  resources :items do
    member do
      get 'select'
    end
    collection do
      get 'menu'
    end
  end

  get 'admin/index'
  get 'homepage/index'
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :venue
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, required: false # See the Readme section about Ghost orders
  belongs_to :table
  has_one :venue, through: :table
  has_many :lines, dependent: :destroy
  has_many :items

  def add(item)
    lines.create!(item: item, price: item.price)
  end

  def total
    lines.sum(&:price)
  end

  def amount
    (total * 100).to_i
  end

  def pay
    self.paid = DateTime.current
    save!
  end

  def produce
    self.produced = DateTime.current
    save!
  end

  def deliver
    self.delivered = DateTime.current
    save!
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :venue
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :venue
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :items
  has_many :tables
  has_many :orders, through: :tables
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?

  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/admin/index.html.erb
<h1>Admin interface</h1>

<ul>
  <li><%= link_to "User", users_path %></li>
  <li><%= link_to "Role", roles_path %></li>
  <li><%= link_to "Venue", venues_path %></li>
  <li><%= link_to "Table", tables_path %></li>
  <li><%= link_to "Items", items_path %></li>
  <li><%= link_to "Order", orders_path %></li>
  <li><%= link_to "Line", lines_path %></li>
</ul>

<%= link_to "Homepage", homepage_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/?advancedFraudSignals=false', 'data-turbolinks-track': 'reload' if @load_stripe %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <b>Bark</b> | <%= link_to "Home", homepage_index_path %> | <%= link_to "Admin", admin_index_path %> | <%= link_to "Manager", manager_index_path %> | <%= link_to "Tables", tables_path %>

    <hr noshade>

    <% flash.each do |key, value| %>
      <p id=<%= key %>><font color=orange><%= value %></font></p>
    <% end %>

    <%= yield %>

  </body>
</html>