config/routes.rb
Rails.application.routes.draw do
  get 'manager/index'
  devise_for :users
  resources :users
  resources :lines
  resources :orders do
    resources :payments, only: [:new] do
      collection do
        get 'success'
      end
    end

    member do
      post 'produce'
      post 'deliver'
    end
  end


  resources :tables do
    member do
      get 'qrcode'
    end
  end
  resources :roles
  resources :venues do
    member do
      get 'produce'
      get 'deliver'
    end
  end
  resources :items do
    member do
      get 'select'
    end
    collection do
      get 'menu'
    end
  end

  get 'admin/index'
  get 'homepage/index'
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :venue
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, required: false # See the Readme section about Ghost orders
  belongs_to :table
  has_one :venue, through: :table
  has_many :lines, dependent: :destroy
  has_many :items

  def add(item)
    lines.create!(item: item, price: item.price)
  end

  def total
    lines.sum(&:price)
  end

  def amount
    (total * 100).to_i
  end

  def pay
    self.paid = DateTime.current
    save!
  end

  def produce
    self.produced = DateTime.current
    save!
  end

  def deliver
    self.delivered = DateTime.current
    save!
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :venue
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :venue
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :items
  has_many :tables
  has_many :orders, through: :tables
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?

  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:menu, :select]
  before_action :set_item, only: [:show, :select, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  def menu
    redirect_to tables_path unless @table = Table.find(cookies[:table_id])
    @items = @table.venue.items.all
    @order = Order.find_by(id: cookies[:order_id]) if cookies[:order_id]
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def select
    # TODO this needs to become a PUT
    redirect_to tables_path unless table = Table.find(cookies[:table_id])
    order = Order.find_by(id: cookies[:order_id]) if cookies[:order_id]
    order = Order.create!(table: table) unless order
    cookies[:order_id] = order.id
    order.add(@item)
    # TODO add multiple items
    redirect_to menu_items_path, notice: "Added #{@item.name}."
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :venue_id)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  require 'rqrcode'
  before_action :set_table, only: [:show, :qrcode, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    # Redirect to the menu for this table.
    cookies[:table_id] = @table.id
    redirect_to menu_items_path
  end

  def qrcode
    render html: RQRCode::QRCode.new(table_url(@table)).as_svg.html_safe
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:description, :venue_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table, local: true) do |form| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.text_field :venue_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Venue</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.description %></td>
        <td><%= link_to table.venue.name, venue_path(table.venue) %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'QRcode', qrcode_table_path(table) %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p>
  <strong>Venue:</strong>
  <%= @table.venue.name %>
</p>

<p>
  <strong>Table:</strong>
  <%= @table.description %>
</p>

<p><strong>Items:</strong></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @table.venue.items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Select', select_item_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>