config/routes.rb
Rails.application.routes.draw do
  get 'manager/index'
  devise_for :users
  resources :users
  resources :lines
  resources :orders do
    resources :payments, only: [:new] do
      collection do
        get 'success'
      end
    end

    member do
      post 'produce'
      post 'deliver'
    end
  end


  resources :tables do
    member do
      get 'qrcode'
    end
  end
  resources :roles
  resources :venues do
    member do
      get 'produce'
      get 'deliver'
    end
  end
  resources :items do
    member do
      get 'select'
    end
    collection do
      get 'menu'
    end
  end

  get 'admin/index'
  get 'homepage/index'
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :venue
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, required: false # See the Readme section about Ghost orders
  belongs_to :table
  has_one :venue, through: :table
  has_many :lines, dependent: :destroy
  has_many :items

  def add(item)
    lines.create!(item: item, price: item.price)
  end

  def total
    lines.sum(&:price)
  end

  def amount
    (total * 100).to_i
  end

  def pay
    self.paid = DateTime.current
    save!
  end

  def produce
    self.produced = DateTime.current
    save!
  end

  def deliver
    self.delivered = DateTime.current
    save!
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :venue
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :venue
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :items
  has_many :tables
  has_many :orders, through: :tables
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?

  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
    if @order.paid
      flash[:notice] = "This order has already been paid"
      redirect_to order_path(@order)
    end
    @load_stripe = true
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: "Order #{@order.id}",
        description: "Payment for order at #{@order.venue.name} for order #{@order.id}",
        amount: @order.amount,
        currency: 'EUR',  # TODO: We have a hardcoded currency
        quantity: 1,
      }],
      success_url: success_order_payments_url(@order),
      cancel_url: order_url(@order) # TODO: we probably want a different URL when it is canceled
    )
  end

  def success
    # TODO: can we create a customer here - we have the email and name from Stripe now
    @order.pay
    flash[:success] = "The order has been paid and will be delivered soon."
    redirect_to order_path(@order)
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/payments/new.html.erb
<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Table:</strong>
  <%= @order.table_id %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @order.paid %>
</p>

<p>
  <strong>Produced::</strong>
  <%= @order.produced %>
</p>

<p>
  <strong>Delivered:</strong>
  <%= @order.delivered %>
</p>

<p>
  <strong>Items:</strong>
  <%= @order.lines.count %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>




<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

<% if @order %>
  <p>Current order:</p>
  <%= link_to 'Pay', new_order_payment_path(@order) %>
  <%= link_to 'Clear order', order_path(@order), method: :delete %>
  <p>
  <% @order.lines.each do |line| %>
    <%= line.item.name %><br>
  <% end %>
  <script>
    var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

    stripe.redirectToCheckout({
      // Make the id field from the Checkout Session creation API response
      // available to this file, so you can provide it as parameter here
      // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
      sessionId: '<%= @session.id %>'
    }).then(function (result) {
      // If `redirectToCheckout` fails due to a browser or network
      // error, display the localized error message to your customer
      // using `result.error.message`.
    });
    </script>

<% end %>