config/routes.rb
Rails.application.routes.draw do
  get 'manager/index'
  devise_for :users
  resources :users
  resources :lines
  resources :orders do
    resources :payments, only: [:new] do
      collection do
        get 'success'
      end
    end

    member do
      post 'produce'
      post 'deliver'
    end
  end


  resources :tables do
    member do
      get 'qrcode'
    end
  end
  resources :roles
  resources :venues do
    member do
      get 'produce'
      get 'deliver'
    end
  end
  resources :items do
    member do
      get 'select'
    end
    collection do
      get 'menu'
    end
  end

  get 'admin/index'
  get 'homepage/index'
  root 'homepage#index'
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :venue
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:menu, :select]
  before_action :set_item, only: [:show, :select, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  def menu
    redirect_to tables_path unless @table = Table.find(cookies[:table_id])
    @items = @table.venue.items.all
    @order = Order.find_by(id: cookies[:order_id]) if cookies[:order_id]
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def select
    # TODO this needs to become a PUT
    redirect_to tables_path unless table = Table.find(cookies[:table_id])
    order = Order.find_by(id: cookies[:order_id]) if cookies[:order_id]
    order = Order.create!(table: table) unless order
    cookies[:order_id] = order.id
    order.add(@item)
    # TODO add multiple items
    redirect_to menu_items_path, notice: "Added #{@item.name}."
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :venue_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.text_field :venue_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/menu.html.erb
<p>
  <strong>Venue:</strong>
  <%= @table.venue.name %>
</p>

<p>
  <strong>Table:</strong>
  <%= @table.description %>
</p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Select', select_item_path(item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path if current_user %>
<br>

<% if @order %>
  <% if @order.paid %>
    <p>Thanks for ordering:</p>
    <%= link_to 'New order', new_order_path %>
  <% else %>
    <p>Current order:</p>
    <%= link_to 'Pay', new_order_payment_path(@order) %>
    <%= link_to 'Clear order', order_path(@order), method: :delete %>
  <% end  %>

  <p>
  <% @order.lines.each do |line| %>
    <%= line.item.name %><br>
  <% end %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>